import React, { useEffect } from 'react';
import { Shield } from 'lucide-react';

const sections = [
  {
    number: '1',
    title: 'Use of the Application',
    content: (
      <>
        <p className="leading-relaxed mb-3">
          AI Risk Navigator ("the Application") is provided as a tool to support analysis of risks associated with artificial intelligence systems in healthcare environments.
        </p>
        <p className="text-sm font-semibold text-slate-700 mb-2">The Application is intended for:</p>
        <ul className="space-y-1 mb-3">
          {['Informational purposes', 'Risk assessment support', 'Governance and compliance analysis'].map((item, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
              <span className="text-teal-600 font-bold mt-0.5">•</span> {item}
            </li>
          ))}
        </ul>
        <p className="text-sm text-slate-600 italic">It is not intended to replace professional judgment.</p>
      </>
    ),
  },
  {
    number: '2',
    title: 'Not Medical or Legal Advice',
    highlight: true,
    content: (
      <>
        <p className="leading-relaxed mb-3 font-medium text-slate-800">
          AI Risk Navigator does not provide medical, clinical, or legal advice.
        </p>
        <p className="text-sm font-semibold text-slate-700 mb-2">Outputs generated by the Application:</p>
        <ul className="space-y-1 mb-4">
          {['Are analytical in nature', 'Are based on user-provided inputs', 'Should not be used as the sole basis for decision-making'].map((item, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
              <span className="text-teal-600 font-bold mt-0.5">•</span> {item}
            </li>
          ))}
        </ul>
        <p className="text-sm font-semibold text-slate-700 mb-2">Users must rely on qualified professionals for:</p>
        <ul className="space-y-1">
          {['Clinical decisions', 'Regulatory interpretation', 'Legal compliance'].map((item, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
              <span className="text-teal-600 font-bold mt-0.5">•</span> {item}
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    number: '3',
    title: 'User Responsibilities',
    content: (
      <>
        <p className="text-sm font-semibold text-slate-700 mb-2">Users agree to:</p>
        <ul className="space-y-1">
          {[
            'Use the Application responsibly',
            'Avoid submitting real patient-identifiable data (ePHI)',
            'Validate all outputs before acting on them',
            'Ensure compliance with applicable laws and policies',
          ].map((item, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
              <span className="text-teal-600 font-bold mt-0.5">•</span> {item}
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    number: '4',
    title: 'Accuracy and Limitations',
    content: (
      <>
        <p className="leading-relaxed mb-3 text-sm text-slate-600">
          While the Application is designed to provide structured and framework-aligned analysis:
        </p>
        <ul className="space-y-1">
          {[
            'Outputs are estimates and interpretations',
            'Results may not be complete or accurate in all cases',
            'The Application does not guarantee identification of all risks',
          ].map((item, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
              <span className="text-teal-600 font-bold mt-0.5">•</span> {item}
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    number: '5',
    title: 'No Warranty',
    content: (
      <>
        <p className="leading-relaxed mb-3 text-sm text-slate-600">
          The Application is provided <span className="italic">"as is"</span> without warranties of any kind, including:
        </p>
        <ul className="space-y-1">
          {['Accuracy', 'Reliability', 'Fitness for a particular purpose'].map((item, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
              <span className="text-teal-600 font-bold mt-0.5">•</span> {item}
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    number: '6',
    title: 'Limitation of Liability',
    content: (
      <>
        <p className="leading-relaxed mb-3 text-sm text-slate-600">
          AI Risk Navigator and its creators are not responsible for:
        </p>
        <ul className="space-y-1">
          {[
            'Decisions made based on Application output',
            'Any direct or indirect damages resulting from use',
          ].map((item, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
              <span className="text-teal-600 font-bold mt-0.5">•</span> {item}
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    number: '7',
    title: 'Acceptable Use',
    content: (
      <>
        <p className="leading-relaxed mb-3 text-sm text-slate-600">Users must not:</p>
        <ul className="space-y-1">
          {[
            'Misuse the Application',
            'Attempt to introduce unlawful or harmful data',
            'Use it in violation of healthcare privacy regulations',
          ].map((item, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
              <span className="text-teal-600 font-bold mt-0.5">•</span> {item}
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    number: '8',
    title: 'Changes to Terms',
    content: (
      <ul className="space-y-1">
        {[
          'These Terms of Use may be updated at any time.',
          'Continued use of the Application indicates acceptance of updated terms.',
        ].map((item, i) => (
          <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
            <span className="text-teal-600 font-bold mt-0.5">•</span> {item}
          </li>
        ))}
      </ul>
    ),
  },
];

export default function TermsOfUse() {
  useEffect(() => { document.title = 'Terms of Use | AI Risk Navigator for Healthcare'; }, []);

  return (
    <div className="max-w-3xl mx-auto px-4 py-16">

      {/* Header */}
      <div className="mb-10">
        <div className="flex items-center gap-2 mb-3">
          <Shield className="h-4 w-4 text-teal-600" />
          <span className="text-teal-600 text-xs font-semibold uppercase tracking-widest">AI Risk Navigator for Healthcare</span>
        </div>
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Use</h1>
        <p className="text-slate-400 text-sm">Effective Date: June 18, 2026</p>
        <div className="mt-4 h-px bg-teal-100" />
      </div>

      {/* Sections */}
      <div className="space-y-8">
        {sections.map((s) => (
          <section
            key={s.number}
            className={`rounded-xl p-6 border ${s.highlight ? 'bg-amber-50 border-amber-200' : 'bg-white border-slate-200'}`}
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-7 h-7 rounded-lg bg-teal-600 text-white text-xs font-bold flex items-center justify-center flex-shrink-0">
                {s.number}
              </div>
              <h2 className="text-base font-bold text-slate-900 tracking-tight">
                {s.title}
                {s.highlight && <span className="ml-2 text-xs font-semibold text-amber-600 uppercase tracking-widest">(Important)</span>}
              </h2>
            </div>
            {s.content}
          </section>
        ))}
      </div>

      {/* Contact */}
      <div className="mt-10 bg-slate-50 border border-slate-200 rounded-xl p-6">
        <div className="flex items-center gap-3 mb-3">
          <div className="w-7 h-7 rounded-lg bg-teal-600 text-white text-xs font-bold flex items-center justify-center flex-shrink-0">
            9
          </div>
          <h2 className="text-base font-bold text-slate-900">Contact</h2>
        </div>
        <p className="text-sm text-slate-600 mb-1">For questions regarding these Terms, contact:</p>
        <p className="text-sm font-semibold text-slate-800">Melissa Tanksley</p>
        <a href="mailto:missy.tanksley@gmail.com" className="text-sm text-teal-600 hover:underline">
          missy.tanksley@gmail.com
        </a>
      </div>

      {/* Footer note */}
      <p className="text-xs text-slate-400 text-center mt-10">
        © 2026 AI Risk Navigator for Healthcare · All rights reserved
      </p>
    </div>
  );
}