import React, { useEffect } from 'react';

export default function TermsOfUse() {
  useEffect(() => { document.title = 'Terms of Use | AI Risk Navigator'; }, []);

  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Use</h1>
      <p className="text-slate-400 text-sm mb-10">Last updated: June 2026</p>

      <div className="space-y-10 text-slate-700">

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-3">Purpose of This Tool</h2>
          <p className="leading-relaxed">
            AI Risk Navigator is provided for informational and analytical purposes only. It is designed to help healthcare organizations, security professionals, and compliance teams structure and document AI-related risk analysis aligned with frameworks such as HIPAA, NIST CSF 2.0, and ISO 27005.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-3">Not a Substitute for Professional Judgment</h2>
          <p className="leading-relaxed">
            The outputs generated by this tool — including risk scores, compliance mappings, and recommendations — are not a substitute for professional legal, clinical, or regulatory advice. They should not be used as the sole basis for clinical decisions, compliance certifications, or legal determinations.
          </p>
          <p className="leading-relaxed mt-3">
            Always involve qualified professionals when making decisions that affect patient safety, regulatory compliance, or organizational risk posture.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-3">No Warranty</h2>
          <p className="leading-relaxed">
            This tool is provided "as is" without warranties of any kind. Risk scores and analysis outputs are AI-generated estimates and may not reflect the full scope of risks present in any given system or environment.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-3">Acceptable Use</h2>
          <p className="leading-relaxed">
            You agree to use AI Risk Navigator only for lawful purposes and in accordance with these terms. You must not attempt to misuse, reverse engineer, or exploit the platform in any way that could harm other users or the integrity of the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-slate-900 mb-3">Changes to These Terms</h2>
          <p className="leading-relaxed">
            We may update these terms from time to time. Continued use of the platform after changes are posted constitutes acceptance of the updated terms.
          </p>
        </section>

      </div>
    </div>
  );
}